### NumPy 中的数组

NumPy提供的最重要的数据结构是一个称为NumPy数组的强大对象。NumPy数组是通常的Python数组的扩展。NumPy数组配备了大量的函数和运算符，可以帮助我们快速编写上面讨论过的各种类型计算的高性能代码。让我们看看如何快速定义一维NumPy数组：

In [2]:
import numpy as np
my_array = np.array([1,2,3,4,5])
print my_array

[1 2 3 4 5]


In [3]:
print type(my_array)#<type 'numpy.ndarray'>

<type 'numpy.ndarray'>


打印数组形状

In [4]:
print my_array.shape

(5L,)


In [ ]:
# print dir(my_array)

In [5]:
import pdir
pdir(my_array)

special attribute:
    __class__, __doc__
abstract class:
    __subclasshook__
arithmetic:
    __abs__, __add__, __and__, __divmod__, __float__, __floordiv__, __iadd__, __iand__, __ifloordiv__, __ilshift__, __imod__, __imul__, __int__, __invert__, __ior__, __ipow__, __irshift__, __isub__, __itruediv__, __ixor__, __lshift__, __mod__, __mul__, __neg__, __or__, __pos__, __pow__, __radd__, __rand__, __rdivmod__, __rfloordiv__, __rlshift__, __rmod__, __rmul__, __ror__, __rpow__, __rrshift__, __rshift__, __rsub__, __rtruediv__, __rxor__, __sub__, __truediv__, __xor__
object customization:
    __format__, __hash__, __init__, __new__, __repr__, __sizeof__, __str__
rich comparison:
    __eq__, __ge__, __gt__, __le__, __lt__, __ne__
attribute access:
    __delattr__, __getattribute__, __setattr__
container:
    __contains__, __delitem__, __getitem__, __iter__, __len__, __setitem__
copy:
    __copy__, __deepcopy__
pickle:
    __reduce__, __reduce_ex__, __setstate__
descriptor:
    T: class getset

打印NumPy数组元素

In [6]:
print my_array[0]
print my_array[1]

1
2


修改NumPy数组的元素

In [7]:
my_array[0] = -1
print my_array

[-1  2  3  4  5]


创建全0/全1数组

In [8]:
my_new_array = np.zeros(5)#zeros: zeros(shape, dtype=float, order='C')
print my_new_array
my_new_array2 = np.ones(5)
print my_new_array2

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]


创建随机值数组

In [9]:
my_random_array = np.random.random(5)#为每个元素分配0到1之间的随机值
print my_random_array 

[ 0.60201171  0.70095134  0.74672373  0.47446177  0.29936291]


创建二维NumPy数组

In [10]:
my_2d_array = np.zeros((2,3))#zeros: zeros(shape, dtype=float, order='C'),shape为指定数组大小的元组
print my_2d_array
my_2d_array2 = np.array([[4, 5, 4], [6, 1, 8],[3, 4, 0],[6, 8 , 3]])
print my_2d_array2
#多维数组可以用 my_array[i][j] 符号来索引，其中i表示行号，j表示列号。i和j都从0开始。
print my_2d_array2[1][1]

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[4 5 4]
 [6 1 8]
 [3 4 0]
 [6 8 3]]
1


In [11]:
pdir(np)

property:
    ALLOW_THREADS, BUFSIZE, CLIP, ERR_CALL, ERR_DEFAULT, ERR_IGNORE, ERR_LOG, ERR_PRINT, ERR_RAISE, ERR_WARN, FLOATING_POINT_SUPPORT, FPE_DIVIDEBYZERO, FPE_INVALID, FPE_OVERFLOW, FPE_UNDERFLOW, False_, Inf, Infinity, MAXDIMS, NAN, NINF, NZERO, NaN, PINF, PZERO, RAISE, SHIFT_DIVIDEBYZERO, SHIFT_INVALID, SHIFT_OVERFLOW, SHIFT_UNDERFLOW, ScalarType, True_, UFUNC_BUFSIZE_DEFAULT, UFUNC_PYVALS_NAME, WRAP, __NUMPY_SETUP__, __all__, __builtins__, __config__, __git_revision__, __mkl_version__, __version__, _import_tools, _mat, abs, absolute, absolute_import, add, add_newdocs, arccos, arccosh, arcsin, arcsinh, arctan, arctan2, arctanh, bitwise_and, bitwise_not, bitwise_or, bitwise_xor, c_, cast, cbrt, ceil, char, compat, conj, conjugate, copysign, core, cos, cosh, ctypeslib, deg2rad, degrees, divide, division, e, emath, equal, euler_gamma, exp, exp2, expm1, fabs, fft, floor, floor_divide, fmax, fmin, fmod, frexp, greater, greater_equal, hypot, index_exp, inf, infty, invert, isfinite, 

提供多维NumPy数组的行/列

In [12]:
print my_2d_array2[:,1]#第二列，index = 1
print my_2d_array2[1,:]#第二行,index = 1

[5 1 4 8]
[6 1 8]


### NumPy中的数组操作

数学运算

In [13]:
import numpy as np 
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
sum = a + b 
difference = a - b 
product = a * b 
quotient = a / b 
print "Sum = \n", sum 
print "Difference = \n", difference 
print "Product = \n", product #乘法运算符执行逐元素乘法而不是矩阵乘法
print "Quotient = \n", quotient 

Sum = 
[[  6.   8.]
 [ 10.  12.]]
Difference = 
[[-4. -4.]
 [-4. -4.]]
Product = 
[[  5.  12.]
 [ 21.  32.]]
Quotient = 
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


矩阵运算

In [14]:
matrix_product = a.dot(b) #矩阵乘法
print "Matrix Product = ", matrix_product

Matrix Product =  [[ 19.  22.]
 [ 43.  50.]]
