# 数组基础

## 创建一个数组

In [1]:
import numpy as np
import pdir
pdir(np)

property:
    ALLOW_THREADS, BUFSIZE, CLIP, ERR_CALL, ERR_DEFAULT, ERR_IGNORE, ERR_LOG, ERR_PRINT, ERR_RAISE, ERR_WARN, FLOATING_POINT_SUPPORT, FPE_DIVIDEBYZERO, FPE_INVALID, FPE_OVERFLOW, FPE_UNDERFLOW, False_, Inf, Infinity, MAXDIMS, NAN, NINF, NZERO, NaN, PINF, PZERO, RAISE, SHIFT_DIVIDEBYZERO, SHIFT_INVALID, SHIFT_OVERFLOW, SHIFT_UNDERFLOW, ScalarType, True_, UFUNC_BUFSIZE_DEFAULT, UFUNC_PYVALS_NAME, WRAP, __NUMPY_SETUP__, __all__, __builtins__, __config__, __git_revision__, __mkl_version__, __version__, _import_tools, _mat, abs, absolute, absolute_import, add, add_newdocs, arccos, arccosh, arcsin, arcsinh, arctan, arctan2, arctanh, bitwise_and, bitwise_not, bitwise_or, bitwise_xor, c_, cast, cbrt, ceil, char, compat, conj, conjugate, copysign, core, cos, cosh, ctypeslib, deg2rad, degrees, divide, division, e, emath, equal, euler_gamma, exp, exp2, expm1, fabs, fft, floor, floor_divide, fmax, fmin, fmod, frexp, greater, greater_equal, hypot, index_exp, inf, infty, invert, isfinite, 

In [3]:
import numpy as np
a1 = np.array([0, 1, 2, 3, 4])#将列表转换为数组,可以传递任何序列（类数组），而不仅仅是常见的列表（list）数据类型。
a2 = np.array((0, 1, 2, 3, 4))#将元组转换为数组
print 'a1:',a1,type(a1)
print 'a2:',a2,type(a2)

a1: [0 1 2 3 4] <type 'numpy.ndarray'>
a2: [0 1 2 3 4] <type 'numpy.ndarray'>


In [4]:
b = np.arange(5) #python内置函数range()的数组版，返回的是numpy ndarrays数组对象，而不是列表
print 'b:',b,type(b)

b: [0 1 2 3 4] <type 'numpy.ndarray'>


In [5]:
c1 = np.ones((3,4))#根据元组指定形状，返回全1数组
c2 = np.ones_like(a1)#以另一个数组为参数，以其形状和dtype创建全1数组
print 'c1',c1,type(c1)
print 'c2',c2,type(c2)

c1 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] <type 'numpy.ndarray'>
c2 [1 1 1 1 1] <type 'numpy.ndarray'>


In [6]:
d1 = np.zeros((5,6))#根据元组指定形状，返回全0数组
d2 = np.zeros_like(c1)#以另一个数组为参数，以其形状和dtype创建全0数组
print 'd1',d1,type(d1)
print 'd2',d2,type(d2)

d1 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]] <type 'numpy.ndarray'>
d2 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] <type 'numpy.ndarray'>


In [7]:
e1 = np.empty((2,3))#创建新数组，只分配内存空间但不填充任何值,不是返回0，而是未初始化的垃圾值
e2 = np.empty_like(d1)#
print 'e1',e1,type(e1)
print 'e2',e2,type(e2)

e1 [[ 0.  0.  0.]
 [ 0.  0.  0.]] <type 'numpy.ndarray'>
e2 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]] <type 'numpy.ndarray'>


In [9]:
f1 = np.eye(3)#创建一个正方的N*N单位矩阵对角线为1，其余为0（）
f2 = np.identity(4)#Return the identity array.
print 'f1',f1,type(f1)
print 'f2',f2,type(f2)

f1 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] <type 'numpy.ndarray'>
f2 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]] <type 'numpy.ndarray'>


In [10]:
g = np.linspace(0, 10, 5) #linspace: Return evenly spaced numbers over a specified interval.
print 'g',g,type(g)

g [  0.    2.5   5.    7.5  10. ] <type 'numpy.ndarray'>


## 数组属性

In [11]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print(type(a)) #<type 'numpy.ndarray'>
print(a.dtype) #int32
print(a.size) #25 Return the number of elements along a given axis.
print(a.shape) #(5L, 5L),Return the shape of an array
print(a.itemsize) #4,itemsize输出array元素的字节数,本例32/8=4
print(a.ndim) #2,Return the number of dimensions of an array

<type 'numpy.ndarray'>
int32
25
(5L, 5L)
4
2


# 使用数组
数组可不必编写循环即可实现循环-数组的矢量化

大小相等的数组之间的任何数学运算都会应用到元素级

大小不相等的数组之间的运算-叫做广播

## 基本操作符-数组四则运算 +、- 、/ 

In [12]:
a = np.arange(25)
print 'a:',a,type(a)
a = a.reshape((5, 5))#Gives a new  shape to an array without changing its data
print 'a:',a,type(a)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <type 'numpy.ndarray'>
a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] <type 'numpy.ndarray'>


In [13]:
b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
print b.shape
b = b.reshape((5,5))
print 'b:',b,type(b)

(25L,)
b: [[10 62  1 14  2]
 [56 79  2  1 45]
 [ 4 92  5 55 63]
 [43 35  6 53 24]
 [56  3 56 44 78]] <type 'numpy.ndarray'>


In [14]:
print(a + b)#逐元素运算,分别对每一个元素进行配对，然后对它们进行运算

[[ 10  63   3  17   6]
 [ 61  85   9   9  54]
 [ 14 103  17  68  77]
 [ 58  51  23  71  43]
 [ 76  24  78  67 102]]


In [15]:
print(a - b)

[[-10 -61   1 -11   2]
 [-51 -73   5   7 -36]
 [  6 -81   7 -42 -49]
 [-28 -19  11 -35  -5]
 [-36  18 -34 -21 -54]]


In [16]:
print(a * b)

[[   0   62    2   42    8]
 [ 280  474   14    8  405]
 [  40 1012   60  715  882]
 [ 645  560  102  954  456]
 [1120   63 1232 1012 1872]]


In [17]:
print(a / b)

[[0 0 2 0 2]
 [0 0 3 8 0]
 [2 0 2 0 0]
 [0 0 2 0 0]
 [0 7 0 0 0]]


In [18]:
print(a ** 2)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [19]:
print(a < b) #逻辑运算符比如 “<” 和 “>” 的时候，返回的将是一个布尔型数组

[[ True  True False  True False]
 [ True  True False False  True]
 [False  True False  True  True]
 [ True  True False  True  True]
 [ True False  True  True  True]]


In [20]:
print(a > b)

[[False False  True False  True]
 [False False  True  True False]
 [ True False  True False False]
 [False False  True False False]
 [False  True False False False]]


In [21]:
print(a.dot(b))#dot() 函数计算两个数组的点积。它返回的是一个标量（只有大小没有方向的一个值）而不是数组

[[ 417  380  254  446  555]
 [1262 1735  604 1281 1615]
 [2107 3090  954 2116 2675]
 [2952 4445 1304 2951 3735]
 [3797 5800 1654 3786 4795]]


## 数组特殊运算符

In [22]:
# sum, min, max, cumsum
a = np.arange(10)
print 'a:',a
print(a.sum()) # >>>45
print(a.min()) # >>>0
print(a.max()) # >>>9
print(a.cumsum()) # >>>[ 0  1  3  6 10 15 21 28 36 45]

a: [0 1 2 3 4 5 6 7 8 9]
45
0
9
[ 0  1  3  6 10 15 21 28 36 45]


# 索引

## 基本索引-整数索引

In [23]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print 'a:',a,type(a)
# 访问元素：二者功能相同
print a[1][3]
print a[1,3]#逗号隔开的索引列表来选取单个元素
# 多维数组中，如果省略了后面的索引，则返回对象是一个维度低一点的数组。
print a[2]

a: [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <type 'numpy.ndarray'>
19
19
[21 22 23 24 25]


## 数组切片
数组切片与列表切片重要区别在于。数组切片是原数组的视图，这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上

In [24]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print 'a:',a
# 单纯切片只能得到相同维度的数组视图，
print(a[::2,::2])
# [[11 13 15]
# [21 23 25]
# [31 33 35]]
print(a[:3,:2])

a: [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[[11 12]
 [16 17]
 [21 22]]


In [25]:
#切片和整数索引混合使用，可以得到低维度的切片
print(a[0, 1:4]) # >>>[12 13 14]
print(a[1:4, 0]) # >>>[16 21 26]
print(a[:, 1]) # >>>[12 17 22 27 32]

[12 13 14]
[16 21 26]
[12 17 22 27 32]


In [26]:
a_slice = a[:,0]#数组切片是原数组的视图，这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上
print 'a_slice:',a_slice
a_slice[:] = 66
print 'a:',a

a_slice: [11 16 21 26 31]
a: [[66 12 13 14 15]
 [66 17 18 19 20]
 [66 22 23 24 25]
 [66 27 28 29 30]
 [66 32 33 34 35]]


In [27]:
#若想要数组切片的一份副本而非视图，则需要显式的进行复制操作
a_slice_copy = a[:,0].copy()
print "a_slice_copy:",a_slice_copy
a_slice_copy[:] = 111
print "a_slice_copy:",a_slice_copy
print 'a:',a

a_slice_copy: [66 66 66 66 66]
a_slice_copy: [111 111 111 111 111]
a: [[66 12 13 14 15]
 [66 17 18 19 20]
 [66 22 23 24 25]
 [66 27 28 29 30]
 [66 32 33 34 35]]


## 布尔型索引
布尔型数组可用于数组索引，通过布尔型数组获取到数组中的数据，将总是创建副本
==，！=，>,<

In [28]:
#数组的比较运算也是矢量化的，会产生一个布尔型数组
names = np.array(['bob','joe','will','bob','will','joe','joe'])
names.shape
names == 'bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [29]:
data = np.random.randn(7,4)
data

array([[ 0.29218127,  0.25302696, -0.08422235, -1.62325209],
       [ 1.17388603, -0.325275  , -0.35192868, -0.81193527],
       [ 0.95988257, -0.01753765,  0.33314724, -3.2986523 ],
       [ 0.53516408,  0.91885145,  0.45288096,  0.88596045],
       [ 0.02117547,  0.82268696,  0.14904166, -0.78678232],
       [ 0.56103622, -1.26473559,  1.39167223, -0.3847038 ],
       [ 0.30724829,  0.30920799,  0.28493466,  1.23220039]])

In [34]:
#布尔型数组可用于数组索引，布尔型数组的长度必须跟被索引的轴长度一致，
#例如names == 'bob'长度为7；data按行索引
#names2 == 'bob'长度为4；data按列索引
print data[names == 'bob']

names2 = names[:4].copy()
print(names2)
print data[:,names2=='bob']

[[   0.29218127  200.          200.            7.        ]
 [   0.53516408  200.          200.            0.88596045]]
['bob' 'joe' 'will' 'bob']
[[   0.29218127    7.        ]
 [ 100.          100.        ]
 [ 100.          100.        ]
 [   0.53516408    0.88596045]
 [ 100.          100.        ]
 [ 100.          100.        ]
 [ 100.          100.        ]]


In [35]:
# 布尔型数组还可以与切片、整数索引混合使用
print data[names == 'bob',1:3]
print data[names == 'bob',1]

[[ 200.  200.]
 [ 200.  200.]]
[ 200.  200.]


In [36]:
# 注意：python关键字and or在布尔型数组中无效
#利用逻辑关系构造复杂布尔型数组,|或，&和，！非
mask = (names !='bob')
print data[mask]
mask = (names =='bob') | (names == 'will')
print data[mask]

[[ 100.  200.  200.  100.]
 [ 100.  200.  200.  100.]
 [ 100.  200.  200.  100.]
 [ 100.  200.  200.  100.]
 [ 100.  200.  200.  100.]]
[[   0.29218127  200.          200.            7.        ]
 [ 100.          200.          200.          100.        ]
 [   0.53516408  200.          200.            0.88596045]
 [ 100.          200.          200.          100.        ]]


In [37]:
# 通过布尔型数组设置值
data[data < 0] = 7
print data
#通过布尔型数组设置整行/整列
data[names !='bob'] = 100
print data

data[:,names2 !='bob'] = 200
print data

[[   0.29218127  200.          200.            7.        ]
 [ 100.          200.          200.          100.        ]
 [ 100.          200.          200.          100.        ]
 [   0.53516408  200.          200.            0.88596045]
 [ 100.          200.          200.          100.        ]
 [ 100.          200.          200.          100.        ]
 [ 100.          200.          200.          100.        ]]
[[   0.29218127  200.          200.            7.        ]
 [ 100.          100.          100.          100.        ]
 [ 100.          100.          100.          100.        ]
 [   0.53516408  200.          200.            0.88596045]
 [ 100.          100.          100.          100.        ]
 [ 100.          100.          100.          100.        ]
 [ 100.          100.          100.          100.        ]]
[[   0.29218127  200.          200.            7.        ]
 [ 100.          200.          200.          100.        ]
 [ 100.          200.          200.          100.     

## 花式索引
花式索引是指利用整数数组进行索引，可以指定顺序选取、

花式索引不同于切片，花式索引总是将数据复制到新数组中

In [ ]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print arr

In [ ]:
#可以指定顺序选取行子集，只需传入一个用于指定顺序的整数列表或数组即可
print arr[[4,3,0,6]]
#使用负数索引将从末尾开始选取行
print arr[[-1,-2]]
#可以同时使用正数和负数进行花式索引
print arr[[1,2,-1,-2]]

In [75]:
#使用多个索引数组，返回的是一个一维数组
arr = np.arange(32).reshape(8,4)
print arr
print arr[[4,3,0,6],[1,2,3,0]]
#获取的元素是（4,1）（3,2）（0,3）（6,0）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[17 14  3 24]


In [76]:
#要想得到矩阵的行列子集（矩形区域）
#方法1
print arr[[4,3,0,6]][:,[1,2,3,0]]
#方法2 np.ix_()用两个一维整数数组转换为一个用于选取方形局域的索引器
print arr[np.ix_([4,3,0,6],[1,2,3,0])]

[[17 18 19 16]
 [13 14 15 12]
 [ 1  2  3  0]
 [25 26 27 24]]
[[17 18 19 16]
 [13 14 15 12]
 [ 1  2  3  0]
 [25 26 27 24]]


## 数组转置和轴对换

In [82]:
# 转置（transpose）返回源数据的视图（不会进行任何复制操作），
# 两种办法实现转置：
# arr.transpose()方法
# arr.T属性
arr = np.arange(15).reshape(3,5)
print arr
print arr.T
print arr.transpose()
#高维数组（>=3维）需要参数：轴编号组成的元组才能对轴进行转置
arr = np.arange(16).reshape(2,2,4)
print arr
print arr.T
print arr.transpose((1,0,2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


## 通用函数-快速的元素级数组函数
对数组中数据进行元素级运算的函数

In [87]:
#一元通用函数，接收一个数组
arr = np.arange(10)
print arr
print np.sqrt(arr)#开方
print np.exp(arr)#指数
print np.square(arr)#平方

[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
#二元通用函数，接收2个数组
x = np.random.randn(5)
print x
y = np.random.randn(5)
print y
print np.add(x,y)#加法
print np.subtract(x,y)#减法
print np.greater(x,y)#元素比较

## 将条件逻辑表述为数组运算
numpy.where()函数是三元表达式 x if condition else y的矢量化版本

In [93]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
condition = np.array([True,False,True,True,False])
# 列表生成式
print [(x if c else y)for x,y,c in zip(xarr,yarr,condition)]
#存在问题
#速度不是很快，原因：纯python实现
#无法用于多维数组

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]


In [97]:
#利用np.where()实现相同功能很简洁
print np.where(condition,xarr,yarr)
#np.where()函数，第2,3参数不一定为数组，也可以为标量值
#where通常用于根据另一个数组生成一个新数组
arr = np.random.randn(4,4)
print arr
print np.where(arr > 0,1,-1)#根据arr原始元素>0,置位1；arr原始元素<0,置位-1
print np.where(arr > 0,1,arr)#根据arr原始元素>0,置位1；arr原始元素<0,保持不变

[ 1.1  2.2  1.3  1.4  2.5]
[[ 1.45968931  0.04416752  0.17823822 -0.39762311]
 [ 1.1620933   0.59377557 -0.23737767 -1.43722256]
 [ 1.03619541 -0.64949799  0.15402381 -0.11071381]
 [ 1.29405992 -0.02742662  0.43881736  1.73837499]]
[[ 1  1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1  1 -1]
 [ 1 -1  1  1]]
[[ 1.          1.          1.         -0.39762311]
 [ 1.          1.         -0.23737767 -1.43722256]
 [ 1.         -0.64949799  1.         -0.11071381]
 [ 1.         -0.02742662  1.          1.        ]]


## 数学和统计方法
数组的数学函数对数组或数组某个轴向的数据进行统计计算；
既可以通过数据实例方法调用；
也可以当做nump顶级函数使用.

In [ ]:
arr = np.arange(10).reshape(2,5)
print arr
print arr.mean()#计算数组平均值
print arr.mean(axis = 0)#可指定轴，用以统计该轴上的值
print arr.mean(axis = 1)
print np.mean(arr)
print np.mean(arr,axis = 0)
print np.mean(arr,axis = 1)

In [ ]:
print arr.sum()#计算数组和
print arr.sum(axis = 0)
print arr.sum(axis = 1)
print np.sum(arr)
print np.sum(arr,axis = 0)
print np.sum(arr,axis = 1)

In [ ]:
print arr.var()#计算方差差
print arr.var(axis = 0)#
print arr.var(axis = 1)#
print np.var(arr)#计算方差差
print np.var(arr,axis = 0)#
print np.var(arr,axis = 1)#

In [ ]:
print arr.std()#计算标准差
print arr.std(axis = 0)#
print arr.std(axis = 1)#
print np.std(arr)#计算标准差
print np.std(arr,axis = 0)#
print np.std(arr,axis = 1)#

In [ ]:
print arr
print arr.min()#计算最小值
print arr.min(axis = 0)#
print arr.min(axis = 1)#
print np.min(arr)#
print np.min(arr,axis = 0)#
print np.min(arr,axis = 1)#

In [111]:
print arr
print arr.max()#计算最大值
print arr.max(axis = 0)#
print arr.max(axis = 1)#
print np.max(arr)
print np.max(arr,axis = 0)#
print np.max(arr,axis = 1)#

[[0 1 2 3 4]
 [5 6 7 8 9]]
9
[5 6 7 8 9]
[4 9]
9
[5 6 7 8 9]
[4 9]


In [ ]:
print arr
print arr[0].argmin()#最小值的索引
print arr[1].argmin()#最小值的索引

print arr[0].argmax()#最大值的索引
print arr[1].argmax()#最大值的索引

In [119]:
print arr
print arr.cumsum()#不聚合，所有元素的累积和，而是返回中间结果构成的数组

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  1  3  6 10 15 21 28 36 45]


In [122]:
arr = arr + 1
print arr
print arr.cumprod()#不聚合，所有元素的累积积，而是返回中间结果构成的数组

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


## 用于布尔型数组的方法
any()测试布尔型数组是否存在一个或多个True

all()检查数组中所有值是否都为True

In [130]:
arr = np.random.randn(10)
# print 
bools = arr > 0
print bools
print bools.any()
print np.any(bools)
print bools.all()
print np.all(bools)

arr = np.array([0,1,2,3,4])
print arr.any()#非布尔型数组，所有非0元素会被当做True

[ True False  True  True  True False  True  True  True False]
True
True
False
False
True


## 排序

In [134]:
arr = np.random.randn(10)
print arr
arr.sort()#与python内置列表排序一样；就地排序，会修改数组本身
print arr
arr = np.random.randn(10)
print arr
print np.sort(arr)#返回数组已排序副本

[ 1.00826129 -1.33200021 -2.09423152  1.14618429 -1.94373366 -1.19964262
 -0.97484352 -0.25508501  0.95594379 -0.92684744]
[-2.09423152 -1.94373366 -1.33200021 -1.19964262 -0.97484352 -0.92684744
 -0.25508501  0.95594379  1.00826129  1.14618429]
[-0.13764091 -0.44657322 -0.4725095  -2.25229905  0.92481373 -0.4272677
 -2.3459137   0.82869414 -0.2215158  -0.28151528]
[-2.3459137  -2.25229905 -0.4725095  -0.44657322 -0.4272677  -0.28151528
 -0.2215158  -0.13764091  0.82869414  0.92481373]


## 唯一化及其他的集合逻辑
numpy针对一维数组的基本集合运算
np.unique()找出数组中的唯一值，并返回已排序的结果

In [138]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
print names
print np.unique(names)

['bob' 'joe' 'will' 'bob' 'will' 'joe' 'joe']
['bob' 'joe' 'will']


## 线性代数

In [145]:
#矩阵乘法
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print x
print y
print x.dot(y)
print np.dot(x,y)

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]
[[ 28  64]
 [ 67 181]]
[[ 28  64]
 [ 67 181]]


## 随机数生成
numpy.random模块对python内置的random进行补充，增接了一些用于高效生成多生概率分布的样本值的函数

In [ ]:
#从给定的上下限范围内随机选取整数
print np.random.randint(10)

In [148]:
#产生正态分布的样本值
print np.random.randn(3,2)

[[-0.05199971 -1.95031704]
 [-1.42560357  0.78544126]
 [ 0.47068984 -0.51157053]]


### 数组组合

In [45]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.arange(6).reshape(2,3)
d = np.arange(2,8).reshape(2,3)
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[4 5 6]
[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]


In [52]:
np.concatenate([c,d])

array([[0, 1, 2],
       [3, 4, 5],
       [2, 3, 4],
       [5, 6, 7]])

In [48]:
# In machine learning, useful to enrich or 
# add new/concatenate features with hstack
np.hstack([c, d])

array([[0, 1, 2, 2, 3, 4],
       [3, 4, 5, 5, 6, 7]])

In [50]:
# Use broadcasting when needed to do this automatically
np.vstack([a,b, d])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])